### ISSUE TITLE
Determination of language by currency won't work

### ISSUE THREAD

**Issue by jschram** [RockyTV/yabpt#16]
[in background.js](https://github.com/RockyTV/yabpt/blob/master/src/background.js#L31) the translation is determined by the selected currency. This brings up issues for users that select EUR as their currency, since this currency is shared by many countries, each with their own languages.

It would be better to have the code use the browser's preferred language, if it's available. This preferred language can be easily read from `window.navigator.languages`

**Comment by Xinayder** [comment]
I was thinking about this just yesterday, I don't know what went in my head when I wrote that code.
