### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Xinayder** [RockyTV/yabpt#2]
If you want to translate yabpt to your native language, here are a few steps to help you get started with it:
- Fork the repository
- Create a folder in `_locales` with the [tag](https://github.com/ystskm/node-localelist/blob/master/lists/_global.txt) of the language you wish to translate the extension to
- Copy the `_locales/en/messages.json` file to the new folder you just created
- Translate and submit a pull request

Please use the following format when creating a new folder for your language: `aa_BB`, where `aa` is the tag and `BB` is the subtag. This may help: https://lh.2xlibre.net/locales/

**Comment by EnrikeGonzaloLegarra** [comment]
I want help with Spanish (Spain)

**Comment by Xinayder** [comment]
@EnrikeGonzaloLegarra read the post.

**Comment by Xinayder** [comment]
Please translate via Crowdin.
