### ISSUE TITLE
Values greater than 9999 are cut off in the badge display

### ISSUE THREAD

**Issue by sparxnet000** [RockyTV/yabpt#28]
With the USD rate of BTC, crossing the 10,000 mark, the extenstion badge is showing **103+** instead of the entire rate. Any chance the 5 digits can be displayed in the badge?

**Comment by Xinayder** [comment]
Sorry for the late response. 

Unfortunately, it's not possible, hence why I changed it to display a '+' sign instead - I thought it would better indicate that there are more digits in question. For example, **12345** would be displayed as **1234**, and after the update it's displayed as **123+**. The badge text is limited to 4 characters only.

**Comment by sparxnet000** [comment]
Is this a Firefox issue? Can it be raised to Mozilla? Instead of the badge, can the icon itself be made up of the digits of the price?

N00b here, so just asking about possible workarounds.

**Comment by Xinayder** [comment]
> Is this a Firefox issue? Can it be raised to Mozilla?

Not only a Firefox issue but a Chrome issue as well. It's _kind of_ a standard to have a badge display 4 digits only.

> Instead of the badge, can the icon itself be made up of the digits of the price?

The icon displayed is 32x32 if I recall correctly, and a new icon would need to be generated for each price change.

I just had an idea that could display more details about the current price, along with the variation compared to the last price, so it'd compare the prices between a 10 minute interval. Since the badge is too limited, maybe a notification could be displayed, showing these details.

**Comment by sparxnet000** [comment]
> Not only a Firefox issue but a Chrome issue as well. It's kind of a standard to have a badge display 4 digits only.

I don't know if it'll help, but I found a Chrome ext that displays the ETH price with 5 digits xxx.xx in the badge. I don't know if Quantum also can do something similar.

[Ethereum Price Ticker | ETH Price](https://chrome.google.com/webstore/detail/ethereum-price-ticker-eth/mbfcnfgpimdeehokhmhdhmpmkphdeamd)

_On an unrelated tangent, any chance of a similar extension for ETH price? AMO seems to be lacking one._

**Comment by Xinayder** [comment]
> I don't know if Quantum also can do something similar.

No, I've tried.

> On an unrelated tangent, any chance of a similar extension for ETH price? AMO seems to be lacking one.

Would it be interesting if this addon displayed ETH price as well?

**Comment by sparxnet000** [comment]
Adding ETH as an option or having a separate discrete extension would always be welcome.

Perhaps adding price sites like coinmarketcap.com or coinranking.com as user configurable options (for more detailed views) might be a way to go, too.

**Comment by Xinayder** [comment]
Just a heads up: I've fixed the issue with price being cut off from the badge text. It only happened in Windows and I just realized (a year later, sorry) that I could've used suffixes for that (i.e. `K, M, B, T, Q`). I've just updated it, so I'm closing this issue. The patch should be up in the marketplaces soon.
